### ISSUE TITLE
Crash on CIA Installing

### ISSUE THREAD

**Issue by ghost** [Pirater12/ocs#13]
I recently wrote a guide on installing boot9strap with OCS. Two users had a bug: the homebrew crashed into CIA installation (luma installation it's OK). If you want more information (like crash dump, etc...) tell me 

Sorry for my bad english, but I'm Italian and I do not know much about English

**Comment by jason0597** [comment]
You mean to say that step1 goes along fine, but once you reboot into Luma and then proceed to do step2 it crashes as soon as you go into 3DS Download play and try to inject the homebrew launcher?

Have these 3DSes been hacked before, or is this the first time?

**Comment by ghost** [comment]
Yes, it crashes on the step2 (both with rosalina and soundhax).
The 3DSes were hacked for the first time

**Comment by jason0597** [comment]
Can you provide ocs.log?

**Comment by ghost** [comment]
I asked the users, as soon as I receive it I'll send it to you

**Comment by ghost** [comment]
The file was not created by the homebrew. It crashes before 2nd step...

**Comment by ghost** [comment]
Up
