### ISSUE TITLE
Help! It cracks when I use OCS

### ISSUE THREAD

**Issue by fenguoerbian** [Pirater12/ocs#9]
I'm hacking a new New3DS following 3ds.guide
At the page "finalizing setup" it recommends OCS.[https://3ds.guide/finalizing-setup](url)
But I only have a poor network environment especially most of amazon.s3 service is blocked by my ISP.
It took infinitly long when I running OCS and it keeps telling me download Fail.
At last I powered off my console.
Now  I re-do everything over, and it keeps cracking when I use OCS. 
It says An Exception Occurred.
In the attachment, there are 3 .dmp files since I tried and faild 3 times, one .log file from OCS, and a photo of what it looks like when I run OCS.
Please, anyone help me.

[3DS.zip](https://github.com/Pirater12/ocs/files/1299035/3DS.zip)

**Comment by hax0kartik** [comment]
No need to worry, you can download those files manually.
First of all download homebrew starter pack from here:-smealum.github.io/3ds/
extract the starter pack and put the contents on the root of your sd(Replacing the boot.3dsx on the sd card with one in the pack)
Grab fbi.3dsx and fbi.cia from here https://github.com/steveice10/fbi/releases/latest
Put fbi.3dsx in a folder named /3ds on the root of your sd and fbi.cia in a folder named cias
Open up fbi.3dsx an from there install fbi.cia
Once you have that, you can install other apps like DSP1 using FBI on your home-menu

**Comment by fenguoerbian** [comment]
Thanks a lot.
I did find an older version of 3ds.guide and have finished install those files manually.
The process is just like you said.
So I think it's OK to close this issue.
